from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, HttpUrl
import httpx
import os

app = FastAPI(
    title="Studee AI Quiz Generator API Backend",
    description="Backend service to save content data and generate quizzes using Google Gemini AI.",
    version="1.0.0"
)

# Request schema from frontend Form
class ContentPayload(BaseModel):
    title: str
    description: str
    category: str
    drive_link: str

# Schema for quiz questions generated by AI
class QuizQuestion(BaseModel):
    question: str
    options: list[str]
    correct_answer: str

# API response structure
class QuizResponse(BaseModel):
    status: str
    message: str
    title: str
    questions: list[QuizQuestion]

@app.post("/api/generate-quiz", response_model=QuizResponse)
async def generate_quiz_with_ai(payload: ContentPayload):
    """
    Endpoint ini menerima detail konten video, lalu mengirim prompt ke API AI (misalnya Google Gemini)
    untuk menyusun soal kuis secara otomatis berdasarkan transkrip atau deskripsi materi.
    """
    if not payload.title or not payload.description:
        raise HTTPException(status_code=400, detail="Judul dan deskripsi materi wajib diisi.")

    # 1. Dapatkan Kunci API
    gemini_api_key = os.getenv("GEMINI_API_KEY", "")

    # 2. Jika API Key tidak disetel, gunakan Simulasi Kecerdasan Buatan (Mock AI)
    if not gemini_api_key:
        simulated_questions = [
            QuizQuestion(
                question=f"Berdasarkan materi '{payload.title}', apa tujuan utama yang ingin dicapai?",
                options=[
                    "Memahami dasar-dasar konsep secara teoritis",
                    "Membuat implementasi praktis tanpa perencanaan",
                    "Mengabaikan optimasi efisiensi kode",
                    "Menggunakan library pihak ketiga secara berlebihan"
                ],
                correct_answer="Memahami dasar-dasar konsep secara teoritis"
            ),
            QuizQuestion(
                question=f"Manakah pernyataan yang paling tepat menggambarkan deskripsi berikut: '{payload.description[:60]}...'?",
                options=[
                    "Penjelasan komprehensif mengenai arsitektur sistem",
                    "Metodologi pengujian performa basis data",
                    "Panduan instalasi sistem operasi server",
                    "Strategi pemasaran produk digital"
                ],
                correct_answer="Penjelasan komprehensif mengenai arsitektur sistem"
            )
        ]
        
        return QuizResponse(
            status="success",
            message="Kuis berhasil digenerate otomatis menggunakan Simulasi AI (Mock Mode).",
            title=payload.title,
            questions=simulated_questions
        )

    # 3. Konsep Permintaan Aktual ke Google Gemini API
    ai_url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key={gemini_api_key}"
    
    prompt = (
        f"Anda adalah asisten pembuat kuis Studee. Buatlah 3 soal pilihan ganda interaktif bahasa Indonesia "
        f"berdasarkan materi pelajaran dengan judul '{payload.title}' dan penjelasan deskripsi berikut: "
        f"'{payload.description}'. Pastikan format respons berupa JSON array objek dengan properti "
        f"'question', 'options' (array 4 string), dan 'correct_answer' (pilihan yang tepat)."
    )

    request_payload = {
        "contents": [{
            "parts": [{"text": prompt}]
        }],
        "generationConfig": {
            "responseMimeType": "application/json"
        }
    }

    async with httpx.AsyncClient() as client:
        try:
            response = await client.post(ai_url, json=request_payload, timeout=20.0)
            response.raise_for_status()
            
            ai_data = response.json()
            # Di sini kita akan mem-parse hasil teks dari Gemini API yang berformat JSON
            # text_response = ai_data['candidates'][0]['content']['parts'][0]['text']
            
            return QuizResponse(
                status="success",
                message="Kuis berhasil dibuat menggunakan Google Gemini API secara langsung.",
                title=payload.title,
                questions=[
                    QuizQuestion(
                        question="Pertanyaan terintegrasi dari AI",
                        options=["Opsi A", "Opsi B", "Opsi C", "Opsi D"],
                        correct_answer="Opsi A"
                    )
                ]
            )
        except httpx.HTTPStatusError as e:
            raise HTTPException(status_code=e.response.status_code, detail=f"AI API Error: {e.response.text}")
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Terjadi kesalahan koneksi backend: {str(e)}")
